# Generated by Django 5.2 on 2025-06-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_course_student_course_section_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Optional: Student's contact number", max_length=15, null=True),
        ),
    ]
